services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached

      # Oscuramento file e directory sensibili
    ports:
      - "3025:3025"
    command: sleep infinity
    working_dir: /workspace